token = "5300266184:AAGEe_MHEAGACDNgeXM3GwgJ_uH4myXu2pA"  # Truth and dare bot


# token= "5525453528:AAE7SUtDLjH1pxHJRlWWHpCHsdkNjM4ehv8


quest = [ "Thanks for this command, Sid is working on this..."]

truth_items = [
               'What is the last lie you told? ',
               'If you could be invisible for a day, what’s the first thing you would do?',
               'What’s the biggest secret you’ve kept from your parents?',
               'What’s the most embarrassing music you listen to?',
               'What’s one thing you love most about yourself?',
               'Who is your secret crush?',
               'Who is the last person you crept on social media?',
               'If a genie granted you three wishes, what would you ask for and why?',
               'What’s your biggest regret?',
               'If you had to only ever watch rom coms or only watch scary movies for the rest of your life, which would you choose and why?',
               'Where is the weirdest place you have ever gone to the bathroom?',
               'Have you ever ghosted on someone?',
               'Which player would survive a zombie apocalypse and which would be the first to go?',
               'Reveal all the details of your first kiss.',
               'What excuse have you used before to get out plans?',
               'What is the longest you have ever slept?',
               'What is the shortest you have ever slept?',
               'Read the last text you sent your best friend or significant other out loud.',
               'What is your biggest pet peeve?',
               'When was the last time you lied?',
               'What five things would you bring to a deserted island?',
               'Which is your favorite Hollywood Chris? Chris Evans, Chris Pratt, Chris Hemsworth or Chris Pine?',
               'What is the most embarrassing thing you ever did on a date?',
               'What is the boldest pickup line you have ever used?',
               'What celebrity do you think you most look like?',
               'How many selfies do you take a day?',
               'What is one thing you would stand in line an hour for?',
               'When was the last time you cried?',
               'What is the longest time you have ever gone without showering?',
               'What is the most embarrassing top-played song on your phone?',
               'What was your favorite childhood show?',
               'If you had to change your name, what would your new first name be?',
               'If you could be a fictional character for a day, who would you choose?',
               'If you could date a fictional character, who would it be?',
               'What is your biggest fear?',
               'What is one silly thing you cannot live without?',
               'Where was your favorite childhood vacation spot?',
               'What is the weirdest trend you have ever participated in?',
               'If you could only listen to one song for the rest of your life, what would you choose?',
               'Who do you text the most?',
               'Have you ever been fired from a job?',
               'If you had to wear only flip-flops or heels for the next 10 years, which would you choose?',
               'What’s an instant deal-breaker in a potential love interest?',
               'If you could go anywhere in the world, where would it be?',
               ' What was the most embarrassing thing you’ve ever done on a date? ',
               ' Have you ever accidentally hit something (or someone!) with your car? ',
               ' Name someone you have pretended to like but actually could not stand',
               ' What is your most bizarre nickname? ',
               ' What is been your most physically painful experience? ',
               ' What bridges are you glad that you burned? ',
               ' What is the craziest thing you’ve done on public transportation? ',
               ' If you met a genie, what would your three wishes be? ',
               ' If you could write anyone on Earth in for President of the United States, who would it be and why? ',
               ' What is the meanest thing you’ve ever said to someone else? ',
               ' Who was your worst kiss ever? ',
               ' What is one thing you’d do if you knew there no consequences? ',
               ' What is the craziest thing you’ve done in front of a mirror? ',
               ' What is the meanest thing you’ve ever said about someone else? ',
               ' What is something you love to do with your friends that you would never do in front of your partner? ',
               ' Who are you most jealous of? ',
               ' What do your favourite pyjamas look like? ',
               ' Have you ever faked sick to get out of a party? ',
               ' Who is the oldest person you’ve dated? ',
               ' How many selfies do you take a day? ',
               ' How many times a week do you wear the same pants? ',
               ' Would you date your high school crush today? ',
               ' Where are you ticklish? ',
               ' Do you believe in any superstitions? If so, which ones? ',
               ' What is one movie you’re embarrassed to admit you enjoy? ',
               ' What is your most embarrassing grooming habit? ',
               ' When is the last time you apologized? What for? ',
               ' How do you feel about the Twilight saga? ',
               ' Where do most of your embarrassing odours come from? ',
               ' Have you ever considered cheating on a partner? ',
               ' Have you ever cheated on a partner? ',
               ' Boxers or briefs? ',
               ' Have you ever peed in a pool? ',
               ' What is the weirdest place you’ve ever grown hair? ',
               ' If you were guaranteed to never get caught, who on Earth would you murder? ',
               ' What is the cheapest gift you’ve ever gotten for someone else? ',
               ' What app do you waste the most time on? ',
               ' What is the weirdest thing you’ve done on a plane? ',
               ' Have you ever been nude in public? ',
               ' How many gossip blogs do you read a day? ',
               ' What is the youngest age partner you’d date? ',
               ' Have you ever picked your nose in public? ',
               ' Have you ever lied about your age? ',
               ' If you had to delete one app from your phone, which one would it be? ',
               ' What is your most embarrassing late-night purchase? ',
               ' What is the longest you’ve gone without showering? ',
               ' Have you ever used a fake ID? ',
               ' Who is your hall pass? ',
               ' Be honest: Do you have a favorite child? ',
               ' Which of your family members annoys you the most and why? ',
               ' What is your greatest fear in a relationship? ',
               ' What is your biggest pet peeve about the person to your left? ',
               ' What is the most embarrassing text in your phone right now? ',
               ' Have you ever seen a dead body? ',
               ' What celebrity do you think is overrated? ',
               ' Have you ever lied to your boss? ',
               ' Have you ever stolen something from work? ',
               ' What is the longest you’ve gone without brushing your teeth? ',
               ' What is your biggest regret in life? ',
               ' Who would you hate to see naked? ',
               ' Describe the weirdest thing you have ever done while inebriated',
               ' Have you ever re-gifted a present? ',
               ' Would you break up with your partner for $ million? ',
               ' Have you ever had a crush on a coworker? ',
               ' Do you still have feelings for any of your exes? ',
               ' What is the smallest tip you’ve ever left at a restaurant? ',
               ' Have you ever regretted something you did to get a crush or partner is attention? ',
               ' What is one job you could never do? ',
               ' Have you ever ghosted a friend? ',
               ' Have you ever ghosted a partner? ',
               ' What is the most scandalous photo in your cloud? ',
               ' If you switched genders for a day, what would you do? ',
               ' How many photo editing apps do you have on your phone? ',
               ' How many pairs of granny panties do you own? ',
               ' What are your favourite and least favourite of your body parts? ',
               ' When was the last time you got dumped? ',
               ' What is the most childish thing you still do? ',
               ' When was the last time you dumped someone? ',
               ' If you had to pick someone in this group to be your partner on a game show, who would it be and why? ',
               ' Would you date someone shorter than you? ',
               ' Have you ever lied to a friend? ',
               ' Name one thing you would change about every person in this group',
               ' When was the last time you made someone else cry? ',
               ' What is the most embarrassing thing you’ve done in front of a crowd? ',
               ' If you could become invisible, what is the worst thing you would do? ',
               ' After you’ve dropped a piece of food, what is the longest time you have left it on the floor before eating it? ',
               ' What is one thing in your life you wish you could change? ',
               ' If you could date two people at once, would you do it? If so, who? ',
               ' What is something that overwhelms you? ',
               ' What was the greatest day of your life? ',
               ' What is one useless skill you’d love to learn anyway? ',
               ' If I went through your cabinets, what is the weirdest thing I’d find? ',
               ' Have you ever farted and blamed it on someone else? ',
               ' What is the worst thing you’ve ever done at work? ',
               ' How many people have you kissed? ',
               ' What is your number? ',
               ' Have you ever gotten mad at a friend for posting an unflattering picture of you? ',
               ' Who in this group would you list as your emergency contact? ',
               ' What is something you would die if your mom found out about? ',
               ' What is the scariest thing that is ever happened to you? ',
               ' If you could set anyone here up with your best friend, who would it be and why? ',
               ' How often do you wash your sheets? ',
               ' Have you ever farted in an elevator? ',
               ' Who was your first love? ',
               ' What is the last purchase you regretted? ',
               ' Have you ever sent a sext? ',
               ' Have you ever sent a sext to the wrong person? Who? ',
               ' What is the weirdest dream you’ve ever had? ',
               ' Have you ever had a one-night stand? ',
               ' Are you scared of getting old? ',
               ' What do you want on your tombstone? ',
               ' If you had one week to live and you had to marry someone in this group, who would it be? ',
               ' What is the last movie that made you cry? ',
               ' List one positive and one negative thing about everyone in the group',
               ' When was your first time? ',
               ' Who was your first? ',
               ' What is the most sinful thing you’ve done in a house of worship? ',
               ' Who would you call to help bury a body? ',
               ' Who would call you to help bury a body? Would you do it? ',
               ' When is the last time you cried and why? ',
               ' What is your favorite possession? ',
               ' Has anyone ever walked in on you in the bathroom? ',
               ' Who in this group would you want to swap lives with for a week? ',
               ' What was your biggest fear as a child? ',
               ' What is your biggest fear today? ',
               ' What is the most embarrassing thing your parents have caught you doing? ',
               ' Name a band you only pretend to like',
               ' What is the last song that made you cry? ',
               ' Have you ever had a wardrobe malfunction? ',
               ' What is the last thing you Googled? ',
               ' What is that one thing you would never do for all the money in the world? ',
               ' Who is your favorite person in your immediate family? ',
               ' If you could only hear one song for the rest of your life, what would it be? ',
               ' When is the last time your partner embarrassed you? ',
               ' What is the last YouTube video you watched? ',
               ' What is the hardest drug you’ve ever tried? ',
               ' When is the last time you peed your pants? ',
               ' Who in this group would be your one phone call if you were in jail? ',
               ' Who do you most often text on the toilet? ',
               ' What is the craziest thing you’ve ever done in a movie theater? ',
               ' What is the craziest thing that has happened to you in a mall? ',
               ' How long was your longest relationship? ',
               ' What is your biggest insecurity? ',
               ' Have you ever been arrested? ',
               ' Who is the most surprising person to ever slide into your DMs? ',
               ' Where is one place you’re dying to visit? ',
               ' What word do you hate the most? ',
               ' What is the most embarrassing thing you’ve ever posted on social media? ',
               ' Have you ever kept a library book? For how long? ',
               ' If you could hire someone to do one thing for you, what would it be? ',
               ' Have you ever lied on your resume? ',
               ' What is the best lie you’ve ever told anyone? ',
               ' Who is the last person you lurked on social media? ',
               ' What is your most embarrassing childhood memory? ',
               ' Have you ever pretended to not get a text to get out of doing something? ',
               ' What is the weirdest thing you’ve ever done in a bathroom? ',
               ' What is the most insane thing you’ve done to get out of a speeding ticket? ',
               ' Do you have any hidden talents? ',
               ' When is the last time you got caught in a lie? ',
               ' How do you really feel about your mother-in-law? ',
               ' What do you think happens when you die? ',
               ' When is the last time you watched an adult movie? ',
               ' Have you ever been in a fight? ',
               ' Would you marry someone rich even if you weren’t in love with them? ',
               ' Have you ever been caught checking someone out? ',
               ' What is the worst advice you’ve ever given someone else? ',
               ' What is the worst advice someone else has ever given you? ',
               ' Would you volunteer as tribute for anyone in this group in The Hunger Games? ',
               ' Is there an ex with whom you’d consider reconciling? ',
               ' What is the weirdest thing you do while driving? ',
               ' Who is the last person who called you? ',
               ' When is the last time you wanted to hit somebody? ',
               ' What is the grossest smell that you secretly enjoy? ',
               ' What is the biggest prank you’ve ever played on someone? ',
               ' What is one thing about your partner that you find least attractive? ',
               ' When was the last time you were outraged? ',
               ' What is your least favorite memory from college? ',
               ' What is the grossest thing that you do alone? ',
               ' Have you ever intentionally sabotaged a coworker? ',
               ' What is your favorite guilty pleasure song? ',
               ' Would you ever get plastic surgery? ',
               ' Have you ever had a near-death experience? ',
               ' What is a skill you wish you had? ',
               ' Have you ever compromised your morals for money? How? ',
               ' Who was the last person you said, “I love you” to? ',
               ' What was your first heartbreak? ',
               ' Have you ever broken someone is heart? ',
               ' Have you ever peed in the shower? ',
               ' What is the most bogus rumor you’ve ever heard about yourself? ',
               ' What is the most bogus rumor you’ve ever spread or heard about someone else? ',
               ' When and where was your first kiss? Who was it with? ',
               ' Do you think cheating can ever be justified? How? ',
               ' Have you ever thrown up in public? ',
               ' When is the last time you got rejected? ',
               ' What is the most common misconception about you? ',
               ' Have you ever seriously injured another person? ',
               ' When did you stop believing in Santa Claus? ',
               ' What is one responsibility you wish you didn’t have? ',
               ' Who is the best kisser you’ve ever had? ',
               ' What is the scariest thing you’ve ever done? ',
               ' Have you ever had a paranormal experience? ',
               ' Have you ever gotten blackout drunk? ',
               ' Do you believe in aliens? ',
               ' What is the pettiest thing you’ve ever done? ',
               ' What is something you’ve done that you still feel guilty about? ',
               ' Have you ever gone skinny dipping? ',
               ' What is the worst date you’ve ever been on? ',
               ' Do you secretly dislike anyone in this group? ',
               ' What is the weirdest thing you’ve ever collected? ',
               ' What is the weirdest thing you’ve ever said to a stranger? ',
               ' Who in this group do you trust the least? ',
               ' What is the most inappropriate time you’ve ever laughed? ',
               ' What is your best pickup line? ',
               ' What is your sleaziest pickup line? ',
               ' What is the weirdest place you’ve ever given or gotten someone is number? ',
               ' What is the dumbest thing you’ve ever lied about? ',
               ' Have you ever said, “I love you” and not really meant it? To whom? ',
               ' What is your least favorite memory from high school? ',
               ' What is the worst present someone has ever given you? ',
               ' When is the last time you shared a toothbrush with someone else? ',
               ' Have you ever had a crush on a boss or teacher? ',
               ' What is the worst present you’ve ever given someone else? ',
               ' What is the weirdest thought you’ve had sitting on a toilet? ',
               ' What song do you sing most in the shower? ',
               ' Do you have a work spouse? ',
               ' What is the cruelest thing you’ve ever done or said to a romantic partner? ',
               ' Who is the person you most regret hooking up with? ',
               ' What is something you’re embarrassed that you’re good at? ',
               ' What was your most humbling moment? ',
               ' Who would you bring with you on a deserted island? ',
               ' What is the worst decision one of the other players has ever made? ',
               ' Have you ever let someone take the blame for something you did? ',
               ' What is the most ridiculous thing you have an emotional attachment to? ',
               ' Have you ever pooped your pants as an adult? ',
               ' What is something you’ve done that you’d judge someone else for doing? ',
               ' What is something weird you do in your sleep? ',
               ' How long have you had your oldest pair of underwear? ',
               ' Who is your hero? ',
               ' Say a quote that inspires you the most? ',
               ' What is something you know you need to do but aren’t looking forward to at all? ',
               ' What is the biggest secret you’ve kept from your parents? ',
               ' What is the most offensive joke you’ve found funny? ',
               ' What are you most proud of in your life? ',
               ' When is the last time you lurked an ex on social media? ',
               ' Would you ever get a prenup? ',
             ]

dare_items = [
               'Set your crush dp as yours',
               'Send a voice note',
               'Send a voice note',
               'Send a voice note',
               'Send a voice note',
               'Send a voice note',
               'Send a voice note',
               'Send a voice note',
               'Send a voice note',
               'Send a voice note',
               'Send a voice note',
               'Send a voice note',
               'Send a voice note',
               'Pick someone in this group and (lovingly) roast them for 2 minutes straight.',
               'Send a heart-eye emoji to your crush’s Instagram story.',
               'Call or text a friend, pretend itiss their birthday, and sing them Happy Birthday to You and, share the proof.',
               'Show us your best dance moves.',
               'Add one of your friend in this group and propose here',
               'Dump out your purse, backpack, or pockets and do a show and tell of what is inside. Record it and send',
               'Prank call one of your family members.',
               'Only send emojis for next 10 mins ',
               'Convey a movie only using emojis',
               'Draw your favorite movie and have the other person guess it (Pictionary-style).',
               'Post the oldest selfie on your phone to Snapchat or Instagram stories (and leave it up!), share the proof',
               'Do karaoke to a song of the groups choosing.',
               'Describe the most attractive quality of every person in the group.',
               'Sing like an opera singer and share the recording.',
               'Make out with a pillow.',
               'Let everyone go through your Snapchat history.',
               'Post a flirty comment on the first Instagram picture that you see. Share the proof',
               'Send the most personal text you have sent in recent days.',
               'Reveal your screen time report',
               'Go outside and howl at the moon.',
               'suggest me more dares',
               'suggest me 2 truths',
               'Do a lyric prank on someone and send the screenshots',
               'tell the saddest story you know',
               'Say something dirty ',
               'Yell out the first word that comes to your mind',
               'Declare your true love',
               'Send your ugliest selfie ',
               'Confess to your current crush',
               'Empty your wallet/purse and show and show what is inside ',
               'Show off your orgasm face',
               'Put as many snacks in your mouth share the clicks',
               'Send a screenshot of your home screen',
               'Give honest review about any 2 members of this group',
               'Tell what you hate about any 2 members of this group',
               'Twerk for a minute ',
               'Tell everyone an embarrassing story about you',
               'Do your best intimate crawl',
               'Send the screenshot of your last online proposal',
               'record "I Love You" and send ',
               'Add five members to the group right now',
               'share your snap chat id',
               'share your Instagram id',
               'share insta id of your crush',
               'share the latest chats with your crush(visible name)',
               'Confess with your crush',
               'Uninstall your IG and share the screenshot',
               'Curse the admin of a different group, in the group chat and share the screenshot',
               'Click the picture of your tongue and send',
               'Delete your phone contact list',
               'Share your recent youtube history',
               'Uninstall 5 Apps from your phone',
               'Tell your darkest fantasy to everyone',
               'Propose a opposite gender in this group ',
               'Propose a opposite gender, whom u hate ',
               'Repeat two words till the admin does not stop you',
               'Share the screenshot of your last online order',
               'Sing a song in a different accent',
               'Left all of the groups except this one',
               'Curse everyone in your dm, and share the screenshots',
               'Share the screenshots of IG chats',
               'Send a screenshot of your selfies gallery.',
               'Try to be funny and make us laugh with your best joke',
               'Google something really intimate and share the screenshot',
               'Write my name on your body with a permanent marker. it can be hidden. take a photo and send it to me.',
               'Send me the 11th picture in your Snapchat/photo gallery.',
               'Send a screenshot of your search history from the past two days',
               'write a love letter and send it to the second person in your dm and send screenshots.',
               'flirt with a random stranger and send in the screenshots.',
               'record yourself doing a catwalk and send it over ',
               'begin your sentences with OMG for the next 5 mins.',
               'draw a tattoo on your bicep and keep it there the entire day. send over a photo of it.',
               'Share the selfie you have last clicked',
               'Share the screenshot of your whatsapp chats',
               'roleplay as a gf/bf with anyone in the group for a whole day',
               'roleplay as a gf/bf with anyone in the group for a whole day',
               'roleplay as a gf/bf with anyone in the group for a whole day',
               'roleplay as a gf/bf with anyone in the group for a whole day',
               'roleplay as a gf/bf with anyone in the group for a whole day',
               'roleplay as a gf/bf with anyone in the group for a whole day',
               'Share the screenshot of your Ex last message…',
               'Call your ex and ask him/her to come back in your life share the call recording',
               'If you do not have a gf/bf make someone from this group(for a day)',
               'Share your last school result with marks',
               'Share your selfie',
               'Show your AADHAR Card pic',
               'Do a prank on someone and share the screenshots',
               'Change your name to Donkey for the day',
               'Show your handwriting',
               'Share the pic of your hand',
               'Post that you love someone from this group and post on IG',
               'Narrate a fake romantic and intimate story of you and your crush',
               'Share the screenshot of your browser search history',
               'Send the screenshot of your bestfriend last messages',
               'Propose someone from this group whom you talk to the most',
               'Show your neckline',
               'Share the screenshot of your notes',
               'Share your favourite sticky note',
               'Share the screenshot of the last, long message you have sent',
               'Share the screenshot of your instagram chats?',
               'Share your instagram drafts',
               'Share the screenshot of your Ex last message…',
               'Show your collarbones…'
             ]

simp_truth = [
               'Your bias?',
               'Have you ever shared your number with a stranger?',
               'Color of your undergarments?',
               'Have you ever kissed someone?',
               'Name the animal you wanna be?',
               'Name a youtube creator you watch?',
               'Are you in love?',
               'Have you ever flirt with an unknown?',
               'What is the craziest thing you’ve done on public transportation?',
               'You ever tried Push bra?',
               'Have you ever clicked a naked picture of you?',
               'Mention a good thing about him/her?',
               'Have you ever tried to make yourself happy physically?',
               'Do you have Abs/figure?', 'Do you have a bf/gf', 'Do you have a gf/bf?',
               'Someone ever touched you romantically?', 'what is your skin color', 'Your age?', 'You ever saw someone naked',
               'The dark secret about you?', 'Your wildest fantasy?', ' Do you overthink?', 'How will you curse someone?',
               'Your naughtiest thought about him/her?'
            ]

simp_dare = [
               'Share the selfie you have last clicked',
               'Share the screenshot of your whatsapp chats',
               'Show your Google History?',
               'Share the screenshot of your Ex last message…',
               'Your address',
               'Do a prank on someone and share the screenshots?',
               'Mimic your father?',
               'Send your voice clip with naughty sounds?',
               'Upload a story on Instagram that U r committed and write my name?',
               'Share the pics of 5 parts of ur body?(do not repeat)',
               'Send the screenshot of your gallery?',
               'Do not text for 5 minute'
            ]
